### ISSUE TITLE
INSTALL

### ISSUE THREAD

**Issue by ghost** [bastiedotorg/quest-of-galaxy#8]
En el instalador no existe la tabla uni1_configuration

**Comment by bastiedotorg** [comment]
Hi,
will be fixed upon next commits. i am reworking the configuration system right now.

table: 
create table uni1_configuration
(
    id           int auto_increment
        primary key,
    universe_id  int         null,
    config_type  varchar(25) null,
    config_value text        null,
    config_key   varchar(55) null,
    constraint uni1_configuration_config_key_universe_id_uindex
        unique (config_key, universe_id)
);
